// <auto-generated />
namespace DoctorWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tbl_new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tbl_new));
        
        string IMigrationMetadata.Id
        {
            get { return "202201160613500_tbl_new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
