// <auto-generated />
namespace DoctorWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_tbls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_tbls));
        
        string IMigrationMetadata.Id
        {
            get { return "202201161352318_new_tbls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
